"""empty message

Revision ID: 78564bafd0ed
Revises: e9187aa579df
Create Date: 2024-08-23 11:22:46.703858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78564bafd0ed'
down_revision = 'e9187aa579df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_lastname_key', type_='unique')
        batch_op.drop_constraint('user_role_key', type_='unique')
        batch_op.drop_column('role')
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_role_key', ['role'])
        batch_op.create_unique_constraint('user_lastname_key', ['lastname'])

    # ### end Alembic commands ###
